### ISSUE TITLE
Error with pad-pack transform dialect script after IREE bump

### ISSUE THREAD

**Issue by erwei-xilinx** [nod-ai/iree-amd-aie#215]
After the recent IREE bump, running the transform dialect script example https://github.com/nod-ai/iree-amd-aie/blob/main/tests/transform_dialect/matmul_fill_spec_pad_pack.mlir gives the following error:

```
<stdin>:3:5: error: could not find a nested named sequence with name: __kernel_config
    hal.executable.variant public @amdaie_xclbin_fb target(<"amd-aie", "amdaie-xclbin-fb", {target_arch = "chip-tbd", ukernels = "none"}>) {
```

The example can work with `iree-opt --iree-transform-dialect-interpreter` after deleting some ops in the transform dialect script. The example is currently not in the CI, as it doesn't have any checks.

**Comment by yzhang93** [comment]
@nirvedhmeshram Can you help take a look at the issue? I think it has something to do with the changes of AIETarget.

**Comment by yzhang93** [comment]
The command I added is not for e2e test with transform dialect. @erwei-xilinx Did you have issue with the above commend or with the full e2e compilation? Can you post your command?

**Comment by erwei-xilinx** [comment]
I had issue with the above command that you posted, @yzhang93 .

**Comment by nirvedhmeshram** [comment]
I took a look, seems like its failing in `TranslateExecutablesPass` and its not amd-aie specific, I tried llvm-cpu backend and failed at the same point with the above mentioned error of `error: could not find a nested named sequence with name: __kernel_config`
I dont have any specific leads on this yet.

**Comment by MaheshRavishankar** [comment]
The transform dialect interpreter flag has changed. I dont know if this works, I ran into this issue recently, but someone could try this 

```
iree-compile --iree-hal-target-backends=amd-aie --compile-to=executable-sources %S/../samples/pad_pack_pipeline_e2e.mlir | iree-opt --pass-pipeline="builtin.module(hal.executable(hal.executable.variant(iree-hal-translate-target-executable-variants{target=amd-aie})))" --iree-codegen-transform-dialect-library=%s@__transform_main
```

**Comment by yzhang93** [comment]
> The transform dialect interpreter flag has changed. I dont know if this works, I ran into this issue recently, but someone could try this
> 
> ```
> iree-compile --iree-hal-target-backends=amd-aie --compile-to=executable-sources %S/../samples/pad_pack_pipeline_e2e.mlir | iree-opt --pass-pipeline="builtin.module(hal.executable(hal.executable.variant(iree-hal-translate-target-executable-variants{target=amd-aie})))" --iree-codegen-transform-dialect-library=%s@__transform_main
> ```

This command works! Thanks @MaheshRavishankar
