### ISSUE TITLE
matmul-elementwise fusion failed to legalize operation 'vector.contract'

### ISSUE THREAD

**Issue by yzhang93** [nod-ai/iree-amd-aie#363]
With the support of fusing consumer (tensor.unpack) into the loop, I've modified the matmul-elementwise fusion with pack-peel pipeline. Now [i32 test](https://github.com/nod-ai/iree-amd-aie/blob/main/tests/samples/pack_peel_pipeline_matmul_elementwise.mlir#L3) compiles and has correct outputs on hardware. However, bf16 test failed at AIE stage with error:

`error: failed to legalize operation 'vector.contract' that was explicitly marked illegal`

I've attached the dump IR here
[afterall_aie.txt](https://github.com/nod-ai/iree-amd-aie/files/15394180/afterall_aie.txt)

Already talked to @erwei-xilinx about the issue, but would like to have more eyes on it, since this seems to be related to the vectorization problem. @newling @jsetoain

**Comment by jsetoain** [comment]
I've taking a look at the first few and they all seem valid, I'll take a closer look tomorrow.

**Comment by newling** [comment]
The vector.contract is all bf16. What is the input IR, does the elementwise operation happen in f32 or bf16? 

Currently we don't support matmul with result type bf16. I've been meaning to improve the error diagnostic error in the case where the matmul is bf16->bf16 as this issue has been encountered at least twice before.

**Comment by yzhang93** [comment]
> The vector.contract is all bf16. What is the input IR, does the elementwise operation happen in f32 or bf16?
> 
> Currently we don't support matmul with result type bf16. I've been meaning to improve the error diagnostic error in the case where the matmul is bf16->bf16 as this issue has been encountered at least twice before.

Okay, I see. The output type of this test is bf16. Let me try another test with elementwise/output operation in f32. 

Then here comes another question... Do you know what is the data type of elementwise op in tres leches bf16 model?

**Comment by yzhang93** [comment]
> > The vector.contract is all bf16. What is the input IR, does the elementwise operation happen in f32 or bf16?
> > Currently we don't support matmul with result type bf16. I've been meaning to improve the error diagnostic error in the case where the matmul is bf16->bf16 as this issue has been encountered at least twice before.
> 
> Okay, I see. The output type of this test is bf16. Let me try another test with elementwise/output operation in f32.
> 
> Then here comes another question... Do you know what is the data type of elementwise op in tres leches bf16 model?

Yes, I just confirmed that if I change the matmul output and elementwise type to f32 it works without problem! @newling Thanks for pointing out the issue.
