### ISSUE TITLE
aie2xclbin peano path: where is libc.a? 

### ISSUE THREAD

**Issue by newling** [nod-ai/iree-amd-aie#411]
In aie2xclbin (in mlir-aie) we're looking for a file libc.a: see here https://github.com/Xilinx/mlir-aie/blob/3ac9566f1da7c4ee6e81c263bc15d92aba7bcae7/tools/aie2xclbin/XCLBinGen.cpp#L345

I can in one of my previous builds of peano that this library was installed, but I can't regenerate it with my current build of peano. It's also not in a wheel from April 30 see https://github.com/Xilinx/llvm-aie/releases 

Is anyone aware of a change, if so what change is needed in XCLBinGen.cpp if there is no libc.a file anymore? Also possible that I'm not configuring cmake correctly anymore. Should this file be in the wheel?

**Comment by makslevental** [comment]
This is because `lib/aie2-none-unknown-elf` isn't currently a part of the llvm-aie wheel distro because wheels aren't [configured to use `Peano.cmake`](https://github.com/Xilinx/llvm-aie/blob/aie-public/.github/workflows/amd_aie_releases/setup.py#L93-L147). I think @jgmelber is working on it.

**Comment by newling** [comment]
If you're saying you have to use [Peano.cmake](https://github.com/Xilinx/llvm-aie/blob/aie-public/clang/cmake/caches/Peano-AIE.cmake) to get lib/aie2-none-unknown-elf/libc.a I don't think that's correct, because we've had libc.a before and never used Peano.cmake

**Comment by newling** [comment]
Is it related to the flag `-DLLVM_LIBC_FULL_BUILD=ON` ?  https://github.com/Xilinx/llvm-aie/blob/abae1617b8de3ab0de36396976cefa79c8a7a5cc/.github/workflows/amd_aie_releases/setup.py#L147

**Comment by newling** [comment]
> This is because `lib/aie2-none-unknown-elf` isn't currently a part of the llvm-aie wheel distro because wheels aren't [configured to use `Peano.cmake`](https://github.com/Xilinx/llvm-aie/blob/aie-public/.github/workflows/amd_aie_releases/setup.py#L93-L147). I think @jgmelber is working on it.

**Comment by newling** [comment]
Just to update, that it would still be really nice if libc.a was part of the wheel, but it still is not (release from 2 days from https://github.com/Xilinx/llvm-aie/releases)

**Comment by makslevental** [comment]
I can update the wheels when I get back (hard to test Peano on my mbp...).

**Comment by newling** [comment]
> I can update the wheels when I get back (hard to test Peano on my mbp...).
Thank you, this will be very useful
