### ISSUE TITLE
Performance and tracing issues when looking at multi dispatch execution

### ISSUE THREAD

**Issue by nirvedhmeshram** [nod-ai/iree-amd-aie#447]
I tried running [this](https://gist.github.com/nirvedhmeshram/784bfb71619187cd70ea932749067bc8) sequence of matmuls IR through the amd-aie hal target and XRT driver. The following [trace](https://sharkpublic.blob.core.windows.net/sharkpublic/nirvedh/xrt_detailed.tracy) was obtained.
There are two observed issues
1. First dispatch took 10 ms (which is expected as this is not on the vectorization path) but the second and third dispatch took 16s each which seems to be a big performance issue.
2. The observation in 1.  was done by looking at the `iree_hal_xrt_direct_command_buffer_dispatch` stats however when we start analyzing real world models we would want to have dispatch specific information about this, when observing traces on cpu backend I do see this information so why is it not there for amd-aie? I did include the following flag `--iree-hal-executable-debug-level=3`in my testing.

**Comment by nirvedhmeshram** [comment]
@ScottTodd maybe you have some thoughts on point 2. I am wondering if its because of it being a external plugin, its a problem?

**Comment by ScottTodd** [comment]
See https://github.com/iree-org/iree/pull/16757 . Executables need to track any debug information they want to be available at runtime, then the runtime needs to tell tracing about that debug information.

**Comment by fifield** [comment]
> 1. First dispatch took 10 ms (which is expected as this is not on the vectorization path) but the second and third dispatch took 16s each which seems to be a big performance issue.

16s is suspicious because it was ([until yesterday](https://github.com/amd/xdna-driver/pull/126)) equal to a timeout in the driver, meaning you may have a hanging kernel: https://github.com/amd/xdna-driver/pull/51, https://github.com/amd/xdna-driver/blob/f839c4e1de4eb790d5307253649e18912e15f8e2/src/driver/amdxdna/aie2_ctx.c#L21

**Comment by nirvedhmeshram** [comment]
> > 1. First dispatch took 10 ms (which is expected as this is not on the vectorization path) but the second and third dispatch took 16s each which seems to be a big performance issue.
> 
> 16s is suspicious because it was ([until yesterday](https://github.com/amd/xdna-driver/pull/126)) equal to a timeout in the driver, meaning you may have a hanging kernel: [amd/xdna-driver#51](https://github.com/amd/xdna-driver/pull/51), https://github.com/amd/xdna-driver/blob/f839c4e1de4eb790d5307253649e18912e15f8e2/src/driver/amdxdna/aie2_ctx.c#L21

I should mention I am having correct numeric though, could it be hanging in some stage before/after executing the kernel? I am working on capturing this with a C++ repro that I can share once I have it.
