### ISSUE TITLE
I8 conv2d vectorization

### ISSUE THREAD

**Issue by erwei-xilinx** [nod-ai/iree-amd-aie#514]
With the following input IR currently there is an issue with lowering the `vector.contract` operation.

```
func.func @conv_2d_nhwc_hwcf(%arg0: tensor<2x14x14x32xi8>, %arg1: tensor<3x3x32x64xi8>) -> tensor<2x12x12x64xi32> {
  %cst = arith.constant 0 : i32
  %0 = tensor.empty() : tensor<2x12x12x64xi32>
  %1 = linalg.fill ins(%cst : i32) outs(%0 : tensor<2x12x12x64xi32>) -> tensor<2x12x12x64xi32>
  %2 = linalg.conv_2d_nhwc_hwcf {dilations = dense<1> : vector<2xi64>, strides = dense<1> : vector<2xi64>} ins(%arg0, %arg1 : tensor<2x14x14x32xi8>, tensor<3x3x32x64xi8>) outs(%1 : tensor<2x12x12x64xi32>) -> tensor<2x12x12x64xi32>
  return %2 : tensor<2x12x12x64xi32>
}
```

Full IR dump: https://gist.github.com/erwei-xilinx/29c5529e166ecfd35a4525f87495e7d0

**Comment by erwei-xilinx** [comment]
Cc: @newling , @yzhang93.

**Comment by erwei-xilinx** [comment]
Error message:

```


/proj/xcohdstaff3/erweiw/iree-ipu/workspace/debug_numerical/elemwise/module_conv_2d_nhwc_hwcf_dispatch_0_amdaie_xclbin_fb/conv_2d_nhwc_hwcf_dispatch_0_conv_2d_nhwc__0.aiecc.mlir:995:11: error: failed to legalize operation 'vector.contract' that was explicitly marked illegal
    %18 = vector.contract {indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d3)>, affine_map<(d0, d1, d2, d3) -> (d3, d2)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel", "reduction"], kind = #vector.kind<add>} %16, %17, %14 : vector<1x4x8xi32>, vector<8x8xi32> into vector<1x4x8xi32>
          ^
/proj/xcohdstaff3/erweiw/iree-ipu/workspace/debug_numerical/elemwise/module_conv_2d_nhwc_hwcf_dispatch_0_amdaie_xclbin_fb/conv_2d_nhwc_hwcf_dispatch_0_conv_2d_nhwc__0.aiecc.mlir:995:11: note: see current operation: %47 = "vector.contract"(%44, %46, %41) <{indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d3)>, affine_map<(d0, d1, d2, d3) -> (d3, d2)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>], iterator_types = [#vector.iterator_type<parallel>, #vector.iterator_type<parallel>, #vector.iterator_type<parallel>, #vector.iterator_type<reduction>], kind = #vector.kind<add>}> : (vector<1x4x8xi32>, vector<8x8xi32>, vector<1x4x8xi32>) -> vector<1x4x8xi32>
/proj/xcohdstaff3/erweiw/iree-ipu/workspace/debug_numerical/elemwise/module_conv_2d_nhwc_hwcf_dispatch_0_amdaie_xclbin_fb/conv_2d_nhwc_hwcf_dispatch_0_conv_2d_nhwc__0.aiecc.mlir:0:0: error: 'builtin.module' op Failed to lower to LLVM
```

**Comment by yzhang93** [comment]
We'll need @jsetoain's insight for this `error: failed to legalize operation 'vector.contract' that was explicitly marked illegal`.

The IR snippet
  ```
   %6 = vector.transfer_read %alloc_23[%c0_13, %c0_13, %c0_13, %c0_13], %c0_i8_14 {in_bounds = [true, true, true]} : memref<1x1x4x8xi8, 2 : i32>, vector<1x4x8xi8>
     %7 = vector.transfer_read %alloc_24[%c0_13, %c0_13, %c0_13, %c0_13], %c0_i8_14 {in_bounds = [true, true, true]} : memref<1x1x8x8xi8, 2 : i32>, vector<1x8x8xi8>
     %8 = vector.transfer_read %alloc_20[%c0_13, %c0_13, %c0_13, %c0_13], %c0_i32_12 {in_bounds = [true, true, true]} : memref<1x1x4x8xi32, 2 : i32>, vector<1x4x8xi32>
     %9 = vector.extract %7[0] : vector<8x8xi8> from vector<1x8x8xi8>
     %10 = arith.extsi %6 : vector<1x4x8xi8> to vector<1x4x8xi32>
     %11 = arith.extsi %9 : vector<8x8xi8> to vector<8x8xi32>
     %12 = vector.contract {indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d3)>, affine_map<(d0, d1, d2, d3) -> (d3, d2)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel", "reduction"], kind = #vector.kind<add>} %10, %11, %8 : vector<1x4x8xi32>, vector<8x8xi32> into vector<1x4x8xi32>
```

**Comment by erwei-xilinx** [comment]
Copied this issue to `mlir-aie` repo, as it might be in the context of mlir-aie vectorization: https://github.com/Xilinx/mlir-aie/issues/1600

**Comment by jsetoain** [comment]
I see two issues with that `vector.contract`. The first one is data types, i32 is not supported by the hardware. The second issue is that the contract doesn't look like a matmul operation. The indexing maps for the innermost iterators are expected to look something like:

```
parallel: affine_map<(..., dn-3, dn-2, dn-1) -> (..., dn-3, dn-1)>
parallel: affine_map<(..., dn-3, dn-2, dn-1) -> (..., dn-1, dn-2)>
reduction: affine_map<(..., dn-3, dn-2, dn-1) -> (..., dn-3, dn-2)>
```

When you try to convert vector to aievec, it will fail to legalize `vector.contract` ops that don't represent a matmul supported by the hardware (or a matmul supported by the hardware with the b operand transpose). For reference, these are the supported types and shapes (leading unit dimensions are ignored for validity):

         lhs                | rhs                | Accumulator
        :------------------:|:------------------:|:-----------------:
         `vector<4x16xi8>`  | `vector<16x8xi4>`  | `vector<4x8xi32>`
         `vector<4x8xi8>`   | `vector<8x8xi8>`   | `vector<4x8xi32>`
         `vector<4x4xi16>`  | `vector<4x8xi8>`   | `vector<4x8xi32>`
         `vector<4x2xi16>`  | `vector<2x8xi16>`  | `vector<4x8xi32>`
         `vector<2x8xi16>`  | `vector<8x8xi8>`   | `vector<2x8xi64>`
         `vector<4x8xi16>`  | `vector<8x4xi8>`   | `vector<4x4xi64>`
         `vector<2x4xi16>`  | `vector<4x8xi16>`  | `vector<2x8xi64>`
         `vector<4x4xi16>`  | `vector<4x4xi16>`  | `vector<4x4xi64>`
         `vector<4x2xi32>`  | `vector<2x4xi16>`  | `vector<4x4xi64>`
         `vector<4x8xbf16>` | `vector<8x4xbf16>` | `vector<4x4xf32>`

**Comment by jsetoain** [comment]
> We'll need @jsetoain's insight for this `error: failed to legalize operation 'vector.contract' that was explicitly marked illegal`.
> 
> The IR snippet
> 
> ```
>  %6 = vector.transfer_read %alloc_23[%c0_13, %c0_13, %c0_13, %c0_13], %c0_i8_14 {in_bounds = [true, true, true]} : memref<1x1x4x8xi8, 2 : i32>, vector<1x4x8xi8>
>    %7 = vector.transfer_read %alloc_24[%c0_13, %c0_13, %c0_13, %c0_13], %c0_i8_14 {in_bounds = [true, true, true]} : memref<1x1x8x8xi8, 2 : i32>, vector<1x8x8xi8>
>    %8 = vector.transfer_read %alloc_20[%c0_13, %c0_13, %c0_13, %c0_13], %c0_i32_12 {in_bounds = [true, true, true]} : memref<1x1x4x8xi32, 2 : i32>, vector<1x4x8xi32>
>    %9 = vector.extract %7[0] : vector<8x8xi8> from vector<1x8x8xi8>
>    %10 = arith.extsi %6 : vector<1x4x8xi8> to vector<1x4x8xi32>
>    %11 = arith.extsi %9 : vector<8x8xi8> to vector<8x8xi32>
>    %12 = vector.contract {indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d0, d1, d3)>, affine_map<(d0, d1, d2, d3) -> (d3, d2)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2)>], iterator_types = ["parallel", "parallel", "parallel", "reduction"], kind = #vector.kind<add>} %10, %11, %8 : vector<1x4x8xi32>, vector<8x8xi32> into vector<1x4x8xi32>
> ```

Can I have a longer snippet? One that includes the surroundings, so I can try to convert it myself?

**Comment by erwei-xilinx** [comment]
> Can I have a longer snippet? One that includes the surroundings, so I can try to convert it myself?

Thanks for the response. The full IR can be found in the IR dump file: https://gist.github.com/erwei-xilinx/29c5529e166ecfd35a4525f87495e7d0

Where the error message happens on line 125023.

**Comment by jsetoain** [comment]
@yzhang93 @erwei-xilinx Are you passing "aie-target=aieml target-backend=llvmir" as a parameters to `-convert-vector-to-aievec`? Because I just tried that snippet and it's converting just fine for me. Into this:

```
    %0 = vector.shape_cast %arg2 : vector<1x4x8xi32> to vector<4x8xi32>
    %1 = vector.shape_cast %arg0 : vector<1x4x8xi8> to vector<4x8xi8>
    %2 = aievec.matmul %1, %arg1, %0 : vector<4x8xi8>, vector<8x8xi8> into vector<4x8xi32>
    %3 = vector.shape_cast %2 : vector<4x8xi32> to vector<1x4x8xi32>
```

**Comment by jsetoain** [comment]
I see what's blocking the pattern matching, it's those odd `vector.extract` ops. There's a pattern that pushes sign extensions close to data sources, and the `vector.extract` ends up between the `vector.contract` and the `arith.extsi` op, which interferes with pattern matching. Since that was added to help with convolution recognition which is not being used, I'll disable that pattern. That should fix your issue.

**Comment by erwei-xilinx** [comment]
> I see what's blocking the pattern matching, it's those odd `vector.extract` ops. There's a pattern that pushes sign extensions close to data sources, and the `vector.extract` ends up between the `vector.contract` and the `arith.extsi` op, which interferes with pattern matching. Since that was added to help with convolution recognition which is not being used, I'll disable that pattern. That should fix your issue.

That would be awesome, thanks!

**Comment by erwei-xilinx** [comment]
> I see what's blocking the pattern matching, it's those odd `vector.extract` ops. There's a pattern that pushes sign extensions close to data sources, and the `vector.extract` ends up between the `vector.contract` and the `arith.extsi` op, which interferes with pattern matching. Since that was added to help with convolution recognition which is not being used, I'll disable that pattern. That should fix your issue.

FYI here is the IR dump for a bf16 vectorized conv2d, which for some reason worked with the `vector.extract`: https://gist.github.com/erwei-xilinx/06593df1fe7013e0d5a2817c2acda3e5

**Comment by jsetoain** [comment]
> > I see what's blocking the pattern matching, it's those odd `vector.extract` ops. There's a pattern that pushes sign extensions close to data sources, and the `vector.extract` ends up between the `vector.contract` and the `arith.extsi` op, which interferes with pattern matching. Since that was added to help with convolution recognition which is not being used, I'll disable that pattern. That should fix your issue.
> 
> FYI here is the IR dump for a bf16 vectorized conv2d, which for some reason worked with the `vector.extract`: https://gist.github.com/erwei-xilinx/06593df1fe7013e0d5a2817c2acda3e5

The pass only hoists sign extension operations, not type widening ops in general 🙂

**Comment by jsetoain** [comment]
Once [PR#1601](https://github.com/Xilinx/mlir-aie/pull/1601) lands, your code should compile e2e.

**Comment by erwei-xilinx** [comment]
> Once [PR#1601](https://github.com/Xilinx/mlir-aie/pull/1601) lands, your code should compile e2e.

Awesome, thanks so much for the swift response! The i8 conv2d worked for me e2e. I've created a PR to iree-amd-aie to include this example: https://github.com/nod-ai/iree-amd-aie/pull/516
