### ISSUE TITLE
Replace `AMDAIETargetModel` with `AMDAIEDeviceModel `

### ISSUE THREAD

**Issue by jtuyls** [nod-ai/iree-amd-aie#520]
Replace the constants in https://github.com/nod-ai/iree-amd-aie/blob/main/compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIETargetModel.h with calls to the `AMDAIEDeviceModel ` once https://github.com/nod-ai/iree-amd-aie/pull/462 has been merged.

**Comment by makslevental** [comment]
Can go here https://github.com/nod-ai/iree-amd-aie/blob/e4f47318470cf6295068592005f47d6f97bdda10/runtime/src/iree-amd-aie/aie_runtime/xaie_hwcfg.c

**Comment by jtuyls** [comment]
Done with https://github.com/nod-ai/iree-amd-aie/pull/534
