### ISSUE TITLE
The reference LLVM version in `mlir-aie` differ from `iree` cause error.

### ISSUE THREAD

**Issue by EllisLambda** [nod-ai/iree-amd-aie#550]
The latest `mlir-aie` uses the new version LLVM commit which contains `llvm::divideCeilSigned`. But `iree` uses the old version. When using CMake to compile the `iree-build`, the compiler uses the llvm headers in `iree` project then errors occur.

**Comment by makslevental** [comment]
We have a script that synchronizes all the dependencies https://github.com/nod-ai/iree-amd-aie/blob/main/sync_deps.py - can you try that and see if it gets things working for you?

**Comment by EllisLambda** [comment]
<pre><font color="#FF5252">FAILED: </font>compiler/plugins/target/AMD-AIE/air/CMakeFiles/iree_target_amd-aie_air_AIRConversionPasses.objects.dir/home/sym/iree-amd-aie/third_party/mlir-air/mlir/lib/Conversion/AIRLoweringPass.cpp.o 
/usr/bin/clang++  -I/home/sym/iree-amd-aie/third_party/mlir-aie/include -I/home/sym/iree-amd-aie/third_party/mlir-air/mlir/include -I/home/sym/iree -I/home/sym/iree-build -I/home/sym/iree-amd-aie/compiler/plugins/target/AMD-AIE -I/home/sym/iree-build/compiler/plugins/target/AMD-AIE -I/home/sym/iree/third_party/llvm-project/llvm/include -I/home/sym/iree-build/llvm-project/include -I/home/sym/iree/third_party/llvm-project/mlir/include -I/home/sym/iree-build/llvm-project/tools/mlir/include -I/home/sym/iree/third_party/llvm-project/lld/include -I/home/sym/iree-build/llvm-project/tools/lld/include -O3 -DNDEBUG -std=gnu++17 -fPIC -fvisibility=hidden -fno-rtti -fno-exceptions -Werror -Wall -Wno-error=deprecated-declarations -Wno-ambiguous-member-template -Wno-char-subscripts -Wno-extern-c-compat -Wno-gnu-alignof-expression -Wno-gnu-variable-sized-type-not-at-end -Wno-ignored-optimization-argument -Wno-invalid-offsetof -Wno-invalid-source-encoding -Wno-mismatched-tags -Wno-pointer-sign -Wno-reserved-user-defined-literal -Wno-return-type-c-linkage -Wno-self-assign-overloaded -Wno-sign-compare -Wno-signed-unsigned-wchar -Wno-strict-overflow -Wno-trigraphs -Wno-unknown-pragmas -Wno-unknown-warning-option -Wno-unused-command-line-argument -Wno-unused-const-variable -Wno-unused-function -Wno-unused-local-typedef -Wno-unused-private-field -Wno-user-defined-warnings -Wno-missing-braces -Wctad-maybe-unsupported -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wfor-loop-analysis -Wformat-security -Wgnu-redeclared-enum -Wimplicit-fallthrough -Winfinite-recursion -Wliteral-conversion -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wself-assign -Wstring-conversion -Wtautological-overlap-compare -Wthread-safety -Wthread-safety-beta -Wunused-comparison -Wvla -fno-lax-vector-conversions -fmacro-prefix-map=/home/sym/iree=iree -MD -MT compiler/plugins/target/AMD-AIE/air/CMakeFiles/iree_target_amd-aie_air_AIRConversionPasses.objects.dir/home/sym/iree-amd-aie/third_party/mlir-air/mlir/lib/Conversion/AIRLoweringPass.cpp.o -MF compiler/plugins/target/AMD-AIE/air/CMakeFiles/iree_target_amd-aie_air_AIRConversionPasses.objects.dir/home/sym/iree-amd-aie/third_party/mlir-air/mlir/lib/Conversion/AIRLoweringPass.cpp.o.d -o compiler/plugins/target/AMD-AIE/air/CMakeFiles/iree_target_amd-aie_air_AIRConversionPasses.objects.dir/home/sym/iree-amd-aie/third_party/mlir-air/mlir/lib/Conversion/AIRLoweringPass.cpp.o -c /home/sym/iree-amd-aie/third_party/mlir-air/mlir/lib/Conversion/AIRLoweringPass.cpp
/home/sym/iree-amd-aie/third_party/mlir-air/mlir/lib/Conversion/AIRLoweringPass.cpp:513:8: error: unused variable &apos;lastStrideConst&apos; [-Werror,-Wunused-variable]
  513 |   auto lastStrideConst = getConstantIntValue(strides.back());
      |        ^~~~~~~~~~~~~~~
1 error generated.
[106/2130] Building CXX object compile...ie/lib/Dialect/AIE/IR/AIEDialect.cpp.o
ninja: build stopped: subcommand failed.
</pre>

**Comment by EllisLambda** [comment]
<pre><font color="#FF5252">FAILED: </font>compiler/plugins/target/AMD-AIE/air/CMakeFiles/iree_target_amd-aie_air_AIRConversionPasses.objects.dir/home/sym/iree-amd-aie/third_party/mlir-air/mlir/lib/Conversion/AIRLoweringPass.cpp.o 
/usr/bin/clang++  -I/home/sym/iree-amd-aie/third_party/mlir-aie/include -I/home/sym/iree-amd-aie/third_party/mlir-air/mlir/include -I/home/sym/iree -I/home/sym/iree-build -I/home/sym/iree-amd-aie/compiler/plugins/target/AMD-AIE -I/home/sym/iree-build/compiler/plugins/target/AMD-AIE -I/home/sym/iree/third_party/llvm-project/llvm/include -I/home/sym/iree-build/llvm-project/include -I/home/sym/iree/third_party/llvm-project/mlir/include -I/home/sym/iree-build/llvm-project/tools/mlir/include -I/home/sym/iree/third_party/llvm-project/lld/include -I/home/sym/iree-build/llvm-project/tools/lld/include -O3 -DNDEBUG -std=gnu++17 -fPIC -fvisibility=hidden -fno-rtti -fno-exceptions -Werror -Wall -Wno-error=deprecated-declarations -Wno-ambiguous-member-template -Wno-char-subscripts -Wno-extern-c-compat -Wno-gnu-alignof-expression -Wno-gnu-variable-sized-type-not-at-end -Wno-ignored-optimization-argument -Wno-invalid-offsetof -Wno-invalid-source-encoding -Wno-mismatched-tags -Wno-pointer-sign -Wno-reserved-user-defined-literal -Wno-return-type-c-linkage -Wno-self-assign-overloaded -Wno-sign-compare -Wno-signed-unsigned-wchar -Wno-strict-overflow -Wno-trigraphs -Wno-unknown-pragmas -Wno-unknown-warning-option -Wno-unused-command-line-argument -Wno-unused-const-variable -Wno-unused-function -Wno-unused-local-typedef -Wno-unused-private-field -Wno-user-defined-warnings -Wno-missing-braces -Wctad-maybe-unsupported -Wfloat-overflow-conversion -Wfloat-zero-conversion -Wfor-loop-analysis -Wformat-security -Wgnu-redeclared-enum -Wimplicit-fallthrough -Winfinite-recursion -Wliteral-conversion -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wself-assign -Wstring-conversion -Wtautological-overlap-compare -Wthread-safety -Wthread-safety-beta -Wunused-comparison -Wvla -fno-lax-vector-conversions -fmacro-prefix-map=/home/sym/iree=iree -MD -MT compiler/plugins/target/AMD-AIE/air/CMakeFiles/iree_target_amd-aie_air_AIRConversionPasses.objects.dir/home/sym/iree-amd-aie/third_party/mlir-air/mlir/lib/Conversion/AIRLoweringPass.cpp.o -MF compiler/plugins/target/AMD-AIE/air/CMakeFiles/iree_target_amd-aie_air_AIRConversionPasses.objects.dir/home/sym/iree-amd-aie/third_party/mlir-air/mlir/lib/Conversion/AIRLoweringPass.cpp.o.d -o compiler/plugins/target/AMD-AIE/air/CMakeFiles/iree_target_amd-aie_air_AIRConversionPasses.objects.dir/home/sym/iree-amd-aie/third_party/mlir-air/mlir/lib/Conversion/AIRLoweringPass.cpp.o -c /home/sym/iree-amd-aie/third_party/mlir-air/mlir/lib/Conversion/AIRLoweringPass.cpp
/home/sym/iree-amd-aie/third_party/mlir-air/mlir/lib/Conversion/AIRLoweringPass.cpp:513:8: error: unused variable &apos;lastStrideConst&apos; [-Werror,-Wunused-variable]
  513 |   auto lastStrideConst = getConstantIntValue(strides.back());
      |        ^~~~~~~~~~~~~~~
1 error generated.
[106/2130] Building CXX object compile...ie/lib/Dialect/AIE/IR/AIEDialect.cpp.o
ninja: build stopped: subcommand failed.
</pre>

**Comment by makslevental** [comment]
Not sure if you closed because you gave up or because you actually fixed after that error but if you still need help feel free to keep posting here/reopen.

**Comment by EllisLambda** [comment]
> Not sure if you closed because you gave up or because you actually fixed after that error but if you still need help feel free to keep posting here/reopen.

Thanks for your answer. The LLVM version problem had been solved. I just closed the issue by mistake. The unused variable error can be solved by using GCC to compile the project, but I think the code should be general for all compilers.

**Comment by makslevental** [comment]
> Thanks for your answer. The LLVM version problem had been solved. I just closed the issue by mistake. The unused variable error can be solved by using GCC to compile the project, but I think the code should be general for all compilers.

Ya I agree - it's just hard because that's a dep and you can't control all of your deps. But that one we can fix.
