### ISSUE TITLE
`me_basic.o` is removed in newer mlir-aie wheel

### ISSUE THREAD

**Issue by erwei-xilinx** [nod-ai/iree-amd-aie#558]
Updating mlir-aie wheel beyond this [commit ](https://github.com/Xilinx/mlir-aie/commit/1acb6fe98e1613bc5e1b6bb8cf02cbf555d2fd3a) causes the CI board tests to fail: https://github.com/nod-ai/iree-amd-aie/actions/runs/9961649815/job/27523979782.

**Comment by erwei-xilinx** [comment]
Cc: @makslevental

**Comment by makslevental** [comment]
after https://github.com/nod-ai/iree-amd-aie/pull/544 we won't need mlir-aie distro because i've put `me_basic.o` in /opt/llvm-aie/lib/aie2-none-elf/`

**Comment by erwei-xilinx** [comment]
I see, thanks.
