### ISSUE TITLE
Matmul-elementwise fusion test failed to legalize operation 'vector.transpose'

### ISSUE THREAD

**Issue by yzhang93** [nod-ai/iree-amd-aie#594]
IR snippet:

```
%60 = vector.transfer_read %buf2[%c0, %c0, %c0, %c0, %c0, %c0], %c0_i32 {in_bounds = [true, true, true, true, true, true]} : memref<1x1x10x10x4x8xi32>, vector<1x1x10x10x4x8xi32>
%61 = vector.transfer_read %buf3[%c0, %c0, %c0], %c0_i32 {in_bounds = [true, true, true]} : memref<1x10x8xi32>, vector<1x10x8xi32>
%62 = vector.broadcast %61 : vector<1x10x8xi32> to vector<1x10x4x1x10x8xi32>
%63 = vector.transpose %62, [0, 3, 4, 1, 2, 5] : vector<1x10x4x1x10x8xi32> to vector<1x1x10x10x4x8xi32>
%64 = arith.addi %60, %63 : vector<1x1x10x10x4x8xi32>
%65 = arith.sitofp %64 : vector<1x1x10x10x4x8xi32> to vector<1x1x10x10x4x8xf32>
%66 = arith.mulf %65, %cst : vector<1x1x10x10x4x8xf32>
%67 = arith.divf %66, %cst_25 : vector<1x1x10x10x4x8xf32>
%68 = math.round %67 : vector<1x1x10x10x4x8xf32>
%69 = arith.addf %68, %cst_26 : vector<1x1x10x10x4x8xf32>
%70 = arith.cmpf ult, %69, %cst_27 : vector<1x1x10x10x4x8xf32>
%71 = arith.cmpf ugt, %69, %cst_28 : vector<1x1x10x10x4x8xf32>
%72 = arith.select %70, %cst_27, %69 : vector<1x1x10x10x4x8xi1>, vector<1x1x10x10x4x8xf32>
%73 = arith.select %71, %cst_28, %72 : vector<1x1x10x10x4x8xi1>, vector<1x1x10x10x4x8xf32>
%74 = arith.fptosi %73 : vector<1x1x10x10x4x8xf32> to vector<1x1x10x10x4x8xi8>
vector.transfer_write %74, %buf4[%c0, %c0, %c0, %c0, %c0, %c0] {in_bounds = [true, true, true, true, true, true]} : vector<1x1x10x10x4x8xi8>, memref<1x1x10x10x4x8xi8>
```

The above IR was vectorized from elementwise op

```
%22 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d2, d3, d4, d5)>, affine_map<(d0, d1, d2, d3, d4, d5) -> (d1, d2, d5)>, affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d2, d3, d4, d5)>], iterator_types = ["parallel", "parallel", "parallel", "parallel", "parallel", "parallel"]} ins(%20, %pack_44 : tensor<1x1x1x2x4x8xi32>, tensor<1x1x8xi32>) outs(%extracted_slice_45 : tensor<1x1x1x2x4x8xi8>) {
    ^bb0(%in: i32, %in_48: i32, %out: i8):
      %23 = arith.addi %in, %in_48 : i32
      %24 = arith.sitofp %23 : i32 to f32
      %25 = arith.mulf %24, %cst : f32
      %26 = arith.divf %25, %cst_8 : f32
      %27 = math.round %26 : f32
      %28 = arith.addf %27, %cst_9 : f32
      %29 = arith.cmpf ult, %28, %cst_10 : f32
      %30 = arith.cmpf ugt, %28, %cst_11 : f32
      %31 = arith.select %29, %cst_10, %28 : f32
      %32 = arith.select %30, %cst_11, %31 : f32
      %33 = arith.fptosi %32 : f32 to i8
      linalg.yield %33 : i8
    } -> tensor<1x1x1x2x4x8xi8>
```

@makslevental @jsetoain Could you help take a look at this error?

**Comment by yzhang93** [comment]
So I looked at the matmul-elementwise test that is working, and found the elementwise op like this

```
%22 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d2, d3, d4, d5)>, affine_map<(d0, d1, d2, d3, d4, d5) -> (d1, d2, d5)>, affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d2, d3, d4, d5)>], iterator_types = ["parallel", "parallel", "parallel", "parallel", "parallel", "parallel"]} ins(%20, %pack_17 : tensor<1x1x1x2x4x8xi32>, tensor<1x1x8xi32>) outs(%extracted_slice_18 : tensor<1x1x1x2x4x8xi32>) {
      ^bb0(%in: i32, %in_21: i32, %out: i32):
        %23 = arith.addi %in, %in_21 : i32
        linalg.yield %23 : i32
      } -> tensor<1x1x1x2x4x8xi32>
```
remains the same (not lowered as vector op) after `AMDAIEVectorization` pass.

**Comment by makslevental** [comment]
I don't have an answer but I'll be able to take a look at this (and the other issue from earlier this week) tomorrow.

**Comment by jsetoain** [comment]
> So I looked at the matmul-elementwise test that is working, and found the elementwise op like this
> 
> ```
> %22 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d2, d3, d4, d5)>, affine_map<(d0, d1, d2, d3, d4, d5) -> (d1, d2, d5)>, affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d2, d3, d4, d5)>], iterator_types = ["parallel", "parallel", "parallel", "parallel", "parallel", "parallel"]} ins(%20, %pack_17 : tensor<1x1x1x2x4x8xi32>, tensor<1x1x8xi32>) outs(%extracted_slice_18 : tensor<1x1x1x2x4x8xi32>) {
>       ^bb0(%in: i32, %in_21: i32, %out: i32):
>         %23 = arith.addi %in, %in_21 : i32
>         linalg.yield %23 : i32
>       } -> tensor<1x1x1x2x4x8xi32>
> ```
> 
> remains the same (not lowered as vector op) after `AMDAIEVectorization` pass. So should this op be vectorized? Or should the op in the first example not be vectorized?

That's not an element-wise op, it's a bunch of them, right? If I'm reading it right, it's adding %pack_17 (<1x1x8xi32>) to %20 (<1x1x1x2x4x8xi32>) on each one of the 8 <8xi32> slices defined by (d3,d4). It can be (and probably should be) lowered to 8 element-wise vector<8xi32> additions, but this should happen as part of IREE. @newling? If it's not being vectorized, then it's being lowered to scalars ops, and those left to the mercy of Peano's auto-vectorizer.

Regarding your first example, this:
```mlir
%62 = vector.broadcast %61 : vector<1x10x8xi32> to vector<1x10x4x1x10x8xi32>
%63 = vector.transpose %62, [0, 3, 4, 1, 2, 5] : vector<1x10x4x1x10x8xi32> to vector<1x1x10x10x4x8xi32>
```

Presents a couple of challenges:

First, that `vector.transpose` can't be handled with vector operations (not in a trivial way, anyway), so your best option is to scalarize it. We could (should) do this in the lowering from vector to aievec, in the first stage (pre-conversion canonicalization).

Second, you're manipulating vectors of 2560b and 102400b, which are not supported by AIE (you might need a Cray machine for those :-P). Those ops need either to be split into several narrower ops, a lot of them; or the `linalg.generic` op itself needs to be vectorized down to narrower vectors.

The support for more general vector broadcasts is in the making.

**Comment by yzhang93** [comment]
> > So I looked at the matmul-elementwise test that is working, and found the elementwise op like this
> > ```
> > %22 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d2, d3, d4, d5)>, affine_map<(d0, d1, d2, d3, d4, d5) -> (d1, d2, d5)>, affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d2, d3, d4, d5)>], iterator_types = ["parallel", "parallel", "parallel", "parallel", "parallel", "parallel"]} ins(%20, %pack_17 : tensor<1x1x1x2x4x8xi32>, tensor<1x1x8xi32>) outs(%extracted_slice_18 : tensor<1x1x1x2x4x8xi32>) {
> >       ^bb0(%in: i32, %in_21: i32, %out: i32):
> >         %23 = arith.addi %in, %in_21 : i32
> >         linalg.yield %23 : i32
> >       } -> tensor<1x1x1x2x4x8xi32>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > remains the same (not lowered as vector op) after `AMDAIEVectorization` pass. So should this op be vectorized? Or should the op in the first example not be vectorized?
> 
> That's not an element-wise op, it's a bunch of them, right? If I'm reading it right, it's adding %pack_17 (<1x1x8xi32>) to %20 (<1x1x1x2x4x8xi32>) on each one of the 8 <8xi32> slices defined by (d3,d4). It can be (and probably should be) lowered to 8 element-wise vector<8xi32> additions, but this should happen as part of IREE. @newling? If it's not being vectorized, then it's being lowered to scalars ops, and those left to the mercy of Peano's auto-vectorizer.

I think the reason it's not vectorized is that the data type is i32, and vectorization codes have the constraints that the bitwidth <= 16 according to https://github.com/nod-ai/iree-amd-aie/blob/main/compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEVectorization.cpp#L49. To confirm any op with i32 data type shouldn't be vectorized right?

**Comment by yzhang93** [comment]
> Regarding your first example, this:
> 
> ```mlir
> %62 = vector.broadcast %61 : vector<1x10x8xi32> to vector<1x10x4x1x10x8xi32>
> %63 = vector.transpose %62, [0, 3, 4, 1, 2, 5] : vector<1x10x4x1x10x8xi32> to vector<1x1x10x10x4x8xi32>
> ```
> 
> Presents a couple of challenges:
> 
> First, that `vector.transpose` can't be handled with vector operations (not in a trivial way, anyway), so your best option is to scalarize it. We could (should) do this in the lowering from vector to aievec, in the first stage (pre-conversion canonicalization).
> 
> Second, you're manipulating vectors of 2560b and 102400b, which are not supported by AIE (you might need a Cray machine for those :-P). Those ops need either to be split into several narrower ops, a lot of them; or the `linalg.generic` op itself needs to be vectorized down to narrower vectors.

So from what I understand the best strategy for now might be not to vectorize such ops? In addition, it looks like only the reads and writes are in vector, and the other operations such as additions are still using scalars.

**Comment by yzhang93** [comment]
> Fun - I know that's re instruction selection but I have no idea why it might fail. How did you disable? Just by not vectorizing the op or what?

Yes, just by not vectorizing the elementwise op. You can try to reproduce with the source IR and changes of codes here https://github.com/yzhang93/iree-amd-aie/commit/01e5edba9b0626f8d8ad4cd6eb35493d667d50d1.

**Comment by makslevental** [comment]
> Yes, just by not vectorizing the elementwise op. You can try to reproduce with the source IR and changes of codes here [yzhang93@01e5edb](https://github.com/yzhang93/iree-amd-aie/commit/01e5edba9b0626f8d8ad4cd6eb35493d667d50d1).

Ok I'll try to repro and see what I can discover by poking/prodding peano.

**Comment by jsetoain** [comment]
> I think the reason it's not vectorized is that the data type is i32, and vectorization codes have the constraints that the bitwidth <= 16 according to https://github.com/nod-ai/iree-amd-aie/blob/main/compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEVectorization.cpp#L49. To confirm any op with i32 data type shouldn't be vectorized right?

It's a bit more nuanced than that. If all you do is `i32`/`fp32` additions/subtractions, then it is possible to use the vector units and accumulator registers[^1]: `@llvm.aie2.add.acc` for i32 and `@llvm.aie2.add.accfloat` for fp32. In this very specific case, it looks like it's possible to use the addition on accumulator registers.

That said, I don't know how well, or poorly, it would do performance-wise.

In any case, if the choice is to not vectorize, then `-convert-vector-to-aievec` should not be invoked because it won't discriminate between things it can translate and things it can't. Maybe we can re-think this approach, and allow some vector ops mixed with scalarized vector ops, but right now the approach is to bail if a non-convertible vector operation makes it through to the pass[^2].

[^1]: It supports 1024-bit vectors.
[^2]: This is not entirely true because there's been some inconsistencies while developing the conversion, but it is the design intention and so this behaviour is the expected behaviour at the moment.
