### ISSUE TITLE
[Runtime] Refactor codes in driver/xrt

### ISSUE THREAD

**Issue by yzhang93** [nod-ai/iree-amd-aie#751]
There have been major runtime changes in IREE since last week https://github.com/iree-org/iree/commits/main/runtime/src/iree/hal, including api changes and a lot of removals (e.g., https://github.com/iree-org/iree/commit/9bbc926a66f5e986c596ce481ad7f05b297f9ade). These have blocked IREE bump to latest.

@makslevental Could you help (or assign someone who is familiar with runtime codes)?

**Comment by makslevental** [comment]
Only person is @nirvedhmeshram but he's a traitor! JK. I'll do it when I get unpacked on Sunday.
