### ISSUE TITLE
[Convolution] Multiple AIE cores objectfifo 'link' issue. 

### ISSUE THREAD

**Issue by newling** [nod-ai/iree-amd-aie#763]
When targeting multiple AIE cores for convolution, the slices of the input image which go the cores overlaps (such is the nature of convolution!). This doesn't work with the objectfifo lowering through AIE, because aie.link ops expect the data that goes to each tile to be mutually exclusive (more specifically, it expects the data to be 'contiguous'). 

The plan is to do some major refactoring of the lowering pipeline with a goal to remove the aie.link operation entirely. Once this is done, I will return to trying to lowering convolution to multiple array tiles.

**Comment by jtuyls** [comment]
@newling This PR takes care of removing the usage of `aie.objectfifo.link` altogether: https://github.com/nod-ai/iree-amd-aie/pull/784
