### ISSUE TITLE
Vectorized matmul performance regression - transfer reads

### ISSUE THREAD

**Issue by jtuyls** [nod-ai/iree-amd-aie#882]
We're seeing performance regression on vectorized matmul, likely caused by the following PR: https://github.com/nod-ai/iree-amd-aie/pull/867, see table below:

Matmul problem size: 512x512x4096 (MxKxN)
Array configuration: 2x2
Vectorization or ukernel or scalar: Vectorization 

| Commit | Latency (us) |
| -------- | ------- |
| 2086718 | 42513    |
| fded307| 20101 |

@newling

**Comment by newling** [comment]
Ok, thanks for triaging @jtuyls. I can definitely believe that #867 introduced the regression. I'll take a look this morning.

**Comment by newling** [comment]
A bit concerning that the regression was so high, suggests there'll be more work than I expected to get convolution performance up. Future problem.
