### ISSUE TITLE
CI system for windows shall use the NPU driver released by Microsoft windows

### ISSUE THREAD

**Issue by dezhiAmd** [nod-ai/iree-amd-aie#902]
On Windows OS, every device driver needs to be signed by Microsoft so that all applications can use the same driver and work together such as MEP is supported by XRT driver (Refer to https://support.microsoft.com/en-us/windows/windows-studio-effects-273c1fa8-2b3f-41b1-a587-7cc7a24b62d8).
This also applies to NPU devices developed by AMD.

Currently the CI computer is not using the NPU driver released by AMD.

**Comment by makslevental** [comment]
> needs to be signed by Microsoft so that all applications can use the same driver and work together such as MEP is supported by XRT driver

Since we don't use any other applications on that runner, this doesn't apply to us. Indeed the playbook instructions literally tell you to regedit out the requirement for signatures. So there's no issue here.

**Comment by dezhiAmd** [comment]
Without using the driver released by Microsoft, the test result on CI may differ from the real system used by general public

**Comment by makslevental** [comment]
> Without using the driver released by Microsoft, the test result on CI may differ from the real system used by general public

We don't support Windows for the "general public" so that's fine. Please don't re-open this issue. We are not going to change the driver on the CI machine.
